### ISSUE TITLE
Unet_model_nbn2_3009_v1.pb (No such file or directory)

### ISSUE THREAD

**Issue by tiago-nyc** [ND-HowardGroup/Image_denoising#1]
Hi

Thanks for making this code available. I've tried to run it but I'm getting the error message below. Any idea what this could be. The directory /Applications/Fiji.app/models/Unet_model_nbn2_3009_v1/ does exist but it's empty.

Thanks

Tiago

```
[Tue Aug 11 10:43:56 EDT 2020] [INFO] [] Version of TensorFlow: TF 1.13.1 CPU
[Tue Aug 11 10:43:56 EDT 2020] [ERROR] [] null
java.io.FileNotFoundException: /Applications/Fiji.app/models/Unet_model_nbn2_3009_v1/Unet_model_nbn2_3009_v1.pb (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.scijava.util.FileUtils.readFile(FileUtils.java:155)
	at net.image.denoising.DefaultTensorFlowService.loadGraph(DefaultTensorFlowService.java:140)
	at net.image.denoising.demo.ImageDenoising.run(ImageDenoising.java:115)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by varunmannam** [comment]
Hi, 

Thank you for checking our image denoising work.

Can you try with the Tewnsorflow 1.12 version instead of the TF 1.13.1 version?
You can go to Fiji -> Edit Options -> Tensorflow and select TF version of 1.12.0 
![image](https://user-images.githubusercontent.com/38203187/89923775-15486280-dbcf-11ea-83d3-e47db955f6d9.png)

Regards
Varun

**Comment by varunmannam** [comment]
Hi, 

Can you please check whether "Tensorflow service" is enabled or not. Tensorflow installation guide is provided here: https://github.com/varunmannam/Image_denoising/blob/master/Image_Denoising_Plugin/Instructions_for_image_denoising_plugin_installation.pdf

Please check from Setp1 to Step5 are performed on the computer where FIJI is installed.

Kindly, let me know the feedback. 
Thanks

Regards
Varun Mannam

**Comment by tiago-nyc** [comment]
Thanks for your quick reply. Tensorflow was installed as described but something weird is happening: I can't use version 1.12.0. I can select it and get a confirmation message message "Installed selected TensorFlow version..." but once I restart ImageJ, it defaults to the previously installed version. It's weird because I can install other versions (1.9.0, 1.13.1, etc). Trying to figure out why this is happening...

**Comment by varunmannam** [comment]
Hi, 

Thank you for your response. 

**Why the folder is empty?** It might be the model is not fully downloaded.
Once we run the plugin, it should automatically download the trained saved model (in.pb), there should be a saved model (in.pb) format. It happens for the first time only, and the rest of the time, the model has already existed. 
This application support maximum of TF version 1.13.0 only. So TF 1.14 is not supported at present. 

Can you try to copy the .pb file from this link "https://github.com/varunmannam/Image_denoising/tree/master/Image_Denoising_Plugin/Trained_model/Unet_model_nbn2_3009_v1" to you Fiji.app/models/ and try to run the plugin one more time with either TF 12.0 and TF 13.1 versions?

Please let me know your feedback. 
Thanks.

Regards
Varun Mannam

**Comment by tiago-nyc** [comment]
Hi Varun

Thanks for the tip. Copying the .pb file solved the problem. The plugin now works with TF 1.13.0.

Thanks for your help

Tiago

**Comment by varunmannam** [comment]
Hi, 

Great to hear that the copying model worked. Hence closing this issue. 
Feel free to open another issue if something is not working. 

Regards
Varun Mannam
